from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import arabic_reshaper
from bidi.algorithm import get_display
from datetime import datetime
import io

# Register a custom font (replace 'path/to/your/font.ttf' with the actual path)
pdfmetrics.registerFont(TTFont('ArabicFont', 'Arial.ttf'))


def generate_pdf(analysis: str, currency: str, language: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                           rightMargin=50, leftMargin=50,
                           topMargin=50, bottomMargin=50)

    titles = {
        "ar": "تقرير مالي شامل",
        "en": "Comprehensive Financial Report",
        "fr": "Rapport Financier Complet"
    }
    title_text = titles.get(language, titles["en"])

    styles = getSampleStyleSheet()
    story = []

    # Header
    header_style = ParagraphStyle('Header',
        fontSize=22, textColor=HexColor('#1a365d'),
        alignment=1, spaceAfter=8, fontName='Helvetica-Bold')
    
    sub_style = ParagraphStyle('Sub',
        fontSize=11, textColor=HexColor('#4a5568'),
        alignment=1, spaceAfter=5)

    body_style = ParagraphStyle('Body',
        fontSize=10, textColor=HexColor('#2d3748'),
        spaceAfter=6, leading=16)

    heading_style = ParagraphStyle('Heading',
        fontSize=13, textColor=HexColor('#2b6cb0'),
        spaceAfter=8, spaceBefore=12,
        fontName='Helvetica-Bold')

    story.append(Paragraph("FinanceAI Pro", header_style))
    story.append(Paragraph(title_text, header_style))
    story.append(Spacer(1, 10))

    # Info table
    info_data = [
        ['Currency / العملة / Devise', currency],
        ['Language / اللغة / Langue', language.upper()],
        ['Date / التاريخ / Date', datetime.now().strftime('%Y-%m-%d %H:%M')]
    ]
    info_table = Table(info_data, colWidths=[3*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), HexColor('#ebf8ff')),
        ('TEXTCOLOR', (0,0), (-1,-1), HexColor('#2d3748')),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, HexColor('#bee3f8')),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [HexColor('#ebf8ff'), HexColor('#ffffff')])
    ]))
    story.append(info_table)
    story.append(Spacer(1, 20))

    # Divider
    story.append(Table([['']], colWidths=[6.5*inch],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 2, HexColor('#3182ce'))])))
    story.append(Spacer(1, 15))

    # Content
    for line in analysis.split('\n'):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 5))
            continue
        if line.startswith('##') or line.startswith('**'):
            line = line.replace('#', '').replace('*', '').strip()
            story.append(Paragraph(line, heading_style))
        elif line.startswith('-') or line.startswith('•'):
            story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;{line}", body_style))
        else:
            story.append(Paragraph(line, body_style))

    # Footer
    story.append(Spacer(1, 30))
    story.append(Table([['']], colWidths=[6.5*inch],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 1, HexColor('#e2e8f0'))])))
    
    footer_style = ParagraphStyle('Footer',
        fontSize=8, textColor=HexColor('#a0aec0'), alignment=1)
    story.append(Paragraph(
        "Generated by FinanceAI Pro | Powered by Claude AI",
        footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import arabic_reshaper
from bidi.algorithm import get_display
from datetime import datetime
import io

# تسجيل الخط العربي
try:
    pdfmetrics.registerFont(TTFont('ArabicFont', 'Arial.ttf'))
except Exception:
    pdfmetrics.registerFont(TTFont('ArabicFont', 'Helvetica'))


def format_arabic(text: str) -> str:
    if not text:
        return ""
    reshaped = arabic_reshaper.reshape(text)
    return get_display(reshaped)


def generate_pdf_ar(analysis: str, currency: str, language: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                           rightMargin=50, leftMargin=50,
                           topMargin=50, bottomMargin=50)

    title_text = format_arabic("تقرير مالي شامل")

    styles = getSampleStyleSheet()
    story = []

    # إعدادات الخطوط والاتجاه لليمين
    header_style = ParagraphStyle('HeaderAR',
        fontSize=22, textColor=HexColor('#1a365d'),
        alignment=1, spaceAfter=8, fontName='ArabicFont')
    
    body_style = ParagraphStyle('BodyAR',
        fontSize=10, textColor=HexColor('#2d3748'),
        spaceAfter=6, leading=16, fontName='ArabicFont', alignment=2)

    heading_style = ParagraphStyle('HeadingAR',
        fontSize=13, textColor=HexColor('#2b6cb0'),
        spaceAfter=8, spaceBefore=12, fontName='ArabicFont', alignment=2)

    story.append(Paragraph("FinanceAI Pro", header_style))
    story.append(Paragraph(title_text, header_style))
    story.append(Spacer(1, 10))

    # جدول المعلومات بالعربي
    info_data = [
        [format_arabic('العملة'), format_arabic(currency)],
        [format_arabic('اللغة'), "AR"],
        [format_arabic('التاريخ'), datetime.now().strftime('%Y-%m-%d %H:%M')]
    ]
    
    info_table_data = []
    for row in info_data:
        info_table_data.append([
            Paragraph(row[0], ParagraphStyle('td1', fontName='ArabicFont', fontSize=10, alignment=2)),
            Paragraph(row[1], ParagraphStyle('td2', fontName='ArabicFont', fontSize=10, alignment=2))
        ])

    info_table = Table(info_table_data, colWidths=[3*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), HexColor('#ebf8ff')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, HexColor('#bee3f8')),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [HexColor('#ebf8ff'), HexColor('#ffffff')])
    ]))
    story.append(info_table)
    story.append(Spacer(1, 20))

    story.append(Table([['']], colWidths=[6.5*inch],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 2, HexColor('#3182ce'))])))
    story.append(Spacer(1, 15))

    # معالجة محتوى التقرير العربي سطر بسطر
    for line in analysis.split('\n'):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 5))
            continue
        if line.startswith('##') or line.startswith('**'):
            line = line.replace('#', '').replace('*', '').strip()
            story.append(Paragraph(format_arabic(line), heading_style))
        elif line.startswith('-') or line.startswith('•'):
            line = line.strip('-').strip('•').strip()
            story.append(Paragraph(f"{format_arabic(line)} •&nbsp;&nbsp;&nbsp;", body_style))
        else:
            story.append(Paragraph(format_arabic(line), body_style))

    story.append(Spacer(1, 30))
    story.append(Table([['']], colWidths=[6.5*inch],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 1, HexColor('#e2e8f0'))])))
    
    footer_style = ParagraphStyle('FooterAR', fontName='ArabicFont', fontSize=8, textColor=HexColor('#a0aec0'), alignment=1)
    story.append(Paragraph(format_arabic("تم التوليد بواسطة FinanceAI Pro | مدعوم بذكاء Claude AI"), footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()