from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime
import io



def generate_pdf(analysis: str, currency: str, language: str) -> bytes:
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                           rightMargin=50, leftMargin=50,
                           topMargin=50, bottomMargin=50)

    titles = {
        "ar": "تقرير مالي شامل",
        "en": "Comprehensive Financial Report",
        "fr": "Rapport Financier Complet"
    }
    title_text = titles.get(language, titles["en"])

    styles = getSampleStyleSheet()
    story = []

    # Header
    header_style = ParagraphStyle('Header',
        fontSize=22, textColor=HexColor('#1a365d'),
        alignment=1, spaceAfter=8, fontName='Helvetica-Bold')
    
    sub_style = ParagraphStyle('Sub',
        fontSize=11, textColor=HexColor('#4a5568'),
        alignment=1, spaceAfter=5)

    body_style = ParagraphStyle('Body',
        fontSize=10, textColor=HexColor('#2d3748'),
        spaceAfter=6, leading=16)

    heading_style = ParagraphStyle('Heading',
        fontSize=13, textColor=HexColor('#2b6cb0'),
        spaceAfter=8, spaceBefore=12,
        fontName='Helvetica-Bold')

    story.append(Paragraph("FinanceAI Pro", header_style))
    story.append(Paragraph(title_text, header_style))
    story.append(Spacer(1, 10))

    # Info table
    info_data = [
        ['Currency / العملة / Devise', currency],
        ['Language / اللغة / Langue', language.upper()],
        ['Date / التاريخ / Date', datetime.now().strftime('%Y-%m-%d %H:%M')]
    ]
    info_table = Table(info_data, colWidths=[3*inch, 4*inch])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), HexColor('#ebf8ff')),
        ('TEXTCOLOR', (0,0), (-1,-1), HexColor('#2d3748')),
        ('FONTSIZE', (0,0), (-1,-1), 10),
        ('PADDING', (0,0), (-1,-1), 8),
        ('GRID', (0,0), (-1,-1), 0.5, HexColor('#bee3f8')),
        ('ROWBACKGROUNDS', (0,0), (-1,-1), [HexColor('#ebf8ff'), HexColor('#ffffff')])
    ]))
    story.append(info_table)
    story.append(Spacer(1, 20))

    # Divider
    story.append(Table([['']], colWidths=[6.5*inch],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 2, HexColor('#3182ce'))])))
    story.append(Spacer(1, 15))

    # Content
    for line in analysis.split('\n'):
        line = line.strip()
        if not line:
            story.append(Spacer(1, 5))
            continue
        if line.startswith('##') or line.startswith('**'):
            line = line.replace('#', '').replace('*', '').strip()
            story.append(Paragraph(line, heading_style))
        elif line.startswith('-') or line.startswith('•'):
            story.append(Paragraph(f"&nbsp;&nbsp;&nbsp;{line}", body_style))
        else:
            story.append(Paragraph(line, body_style))

    # Footer
    story.append(Spacer(1, 30))
    story.append(Table([['']], colWidths=[6.5*inch],
        style=TableStyle([('LINEABOVE', (0,0), (-1,0), 1, HexColor('#e2e8f0'))])))
    
    footer_style = ParagraphStyle('Footer',
        fontSize=8, textColor=HexColor('#a0aec0'), alignment=1)
    story.append(Paragraph(
        "Generated by FinanceAI Pro | Powered by Claude AI",
        footer_style))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()